# fly.toml file generated for osusu on 2023-04-09T09:45:52-07:00

app = "osusu"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sjc"
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[build.args]
BP_KEEP_FILES = "web/*"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
