package main

// allCuisines are all of the cuisines possible
var allCuisines = []string{"African", "American", "Anglo-Indian", "Arabian", "Argentine", "Armenian", "Australian", "Austrian", "Azeri",
	"Balkan", "Bangladeshi", "Barbeque", "Basque", "Belgian", "Bengali", "Bhutanese", "Bolivian", "Brazilian", "British",
	"Bruneian", "Bulgarian", "Burmese", "Cambodian", "Cantonese", "Cape Malay", "Central Asian", "Cherokee", "Chilean",
	"Chinese", "Colombian", "Cornish", "Costa Rican", "Croatian", "Cuban", "Cypriot", "Czech", "Danish", "Djiboutian",
	"Dominican", "Dutch", "East African", "Eastern European", "Ecuadorian", "Egyptian", "Eritrean", "Estonian",
	"Ethiopian", "Faroe Islands", "Filipino", "Finnish", "French", "Galician", "Gambian", "Georgian", "German",
	"Ghanaian", "Greek", "Grenadian", "Guatemalan", "Guinea-Bissauan", "Guyanese", "Haitian", "Hawaiian", "Herzegovinian",
	"Hungarian", "Icelandic", "Indian", "Indonesian", "Iranian", "Iraqi", "Irish", "Israeli", "Italian",
	"Jamaican", "Japanese", "Jordanian", "Kazakh", "Kenyan", "Khmer", "Korean", "Kosovan", "Kuwaiti",
	"Kyrgyz", "Laotian", "Latin American", "Latvian", "Lebanese", "Lithuanian", "Luxembourgish", "Macedonian",
	"Malagasy", "Malaysian", "Maldivian", "Maltese", "Marshallese", "Mauritanian", "Mauritian", "Mexican",
	"Micronesian", "Middle Eastern", "Mongolian", "Moroccan", "Mozambican", "Myanmar", "Namibian", "Nepalese",
	"New Zealand", "Nicaraguan", "Nigerian", "North African", "North American", "Norwegian", "Omani", "Pakistani",
	"Palauan", "Palestinian", "Panamanian", "Papua New Guinean", "Paraguayan", "Peruvian", "Philippine",
	"Polish", "Portuguese", "Qatari", "Romanian", "Russian", "Rwandan", "Saint Lucian", "Salvadoran", "Samoa",
	"Samoan", "Sanmarinese", "Sao Tome and Principe", "Saudi Arabian", "Scottish", "Senegalese", "Serbian",
	"Seychellois", "Sierra Leonean", "Singaporean", "Slovak", "Slovenian", "Solomon Islander", "Somali",
	"South African", "South American", "South Korean", "Spanish", "Sri Lankan", "Sudanese", "Surinamese",
	"Swazi", "Swedish", "Swiss", "Syrian", "Taiwanese", "Tajikistani", "Tanzanian", "Thai", "Tibetan",
	"Tonga", "Trinidad and Tobago", "Tunisian", "Turkish", "Turkmen", "Tuvaluan", "Ugandan", "Ukrainian",
	"Uruguayan", "Uzbek", "Vietnamese", "Welsh", "West African", "Western European", "Yemeni", "Zambian",
	"Zimbabwean"}

// cuisineWords are all of the words associated with different cuisines
var cuisineWords = map[string][]string{
	"African": {
		"rice",
		"yams",
		"plantains",
		"maize",
		"millet",
		"sorghum",
		"cassava",
		"taro",
		"sweet potatoes",
		"peanuts",
		"groundnuts",
		"beans",
		"lentils",
		"okra",
		"spinach",
		"collard greens",
		"mustard greens",
		"turnips",
		"beets",
		"cabbage",
		"tomatoes",
		"peppers",
		"onions",
		"garlic",
		"ginger",
		"cilantro",
		"mint",
		"curry leaves",
		"thyme",
		"rosemary",
		"basil",
		"parsley",
		"lemons",
		"limes",
		"oranges",
		"bananas",
		"mangoes",
		"papayas",
		"guavas",
		"pineapples",
		"avocados",
		"coconuts",
		"honey",
		"molasses",
		"butter",
		"oil",
		"vinegar",
		"salt",
		"pepper",
	},
}
